// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// dotenv/config だと .env しか読まないため、Supabaseの接続文字列を置いている
// .env.local を明示的に読み込む(Next.jsの実行時とは別に、CLIはこれをしないと拾えない)
loadEnv({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // migrate はプールされた接続(pgbouncer, ポート6543)だと prepared statement が
    // 使えず失敗することがあるため、セッション/直接接続(ポート5432)の DIRECT_URL を使う
    url: process.env["DIRECT_URL"],
  },
});
